export type Announcement = {
  id: number;
  user: {
    name: string;
    avatarUrl: string;
  };
  title: string;
  location: string;
  description: string;
  tags: string[];
};

export const mockAnnouncements: Announcement[] = [
  {
    id: 1,
    user: { name: "Carla Dias", avatarUrl: "https://i.pravatar.cc/150?img=1" },
    title: "Procura-se baixista para banda de Rock",
    location: "São Paulo, SP",
    description: "Somos uma banda de rock alternativo com repertório autoral e alguns covers. Procuramos um baixista comprometido para ensaios semanais e shows.",
    tags: ["Baixo", "Rock", "Entrar em uma banda"],
  },
  {
    id: 2,
    user: { name: "Marcos Andrade", avatarUrl: "https://i.pravatar.cc/150?img=2" },
    title: "Vocalista disponível para projetos",
    location: "Rio de Janeiro, RJ",
    description: "Sou vocalista com experiência em MPB e Bossa Nova. Tenho disponibilidade para shows em bares, eventos e gravações. Timbre suave.",
    tags: ["Vocal", "MPB", "Freelancer", "Show/Evento"],
  },
  {
    id: 3,
    user: { name: "Banda Scapegoat", avatarUrl: "https://i.pravatar.cc/150?img=3" },
    title: "Baterista para banda de Metal",
    location: "Belo Horizonte, MG",
    description: "Procuramos um baterista versátil e com pegada para completar nossa formação. Ensaiamos aos sábados. Influências: Metallica, Pantera.",
    tags: ["Bateria", "Metal", "Entrar em uma banda"],
  },
  {
    id: 4,
    user: { name: "Juliana Lima", avatarUrl: "https://i.pravatar.cc/150?img=5" },
    title: "Tecladista para banda de Pop Rock",
    location: "Curitiba, PR",
    description: "Banda de pop rock com agenda de shows procura tecladista com equipamento próprio. Ensaios duas vezes por semana.",
    tags: ["Teclado", "Pop", "Rock", "Entrar em uma banda"],
  },
  {
    id: 5,
    user: { name: "Fernando Alves", avatarUrl: "https://i.pravatar.cc/150?img=6" },
    title: "Guitarrista para gravações",
    location: "Porto Alegre, RS",
    description: "Ofereço meus serviços como guitarrista para gravação de trilhas, jingles e álbuns. Toco diversos estilos, do Jazz ao Metal.",
    tags: ["Guitarra", "Jazz", "Metal", "Gravação"],
  },
  {
    id: 6,
    user: { name: "Coletivo Samba Bom", avatarUrl: "https://i.pravatar.cc/150?img=7" },
    title: "Percussionista para grupo de Samba",
    location: "Salvador, BA",
    description: "Grupo de samba de raiz busca percussionista (pandeiro, tantã) para apresentações em rodas de samba e eventos.",
    tags: ["Percussão", "Samba", "Show/Evento"],
  },
  {
    id: 7,
    user: { name: "Sofia Ribeiro", avatarUrl: "https://i.pravatar.cc/150?img=8" },
    title: "Violinista para casamentos e eventos",
    location: "Fortaleza, CE",
    description: "Violinista com repertório clássico e popular para cerimônias de casamento, recepções e eventos corporativos.",
    tags: ["Violino", "Clássico", "Show/Evento"],
  },
  {
    id: 8,
    user: { name: "Lucas Martins", avatarUrl: "https://i.pravatar.cc/150?img=9" },
    title: "Produtor musical busca novos talentos",
    location: "Recife, PE",
    description: "Estúdio de gravação procura artistas e bandas para produção musical. Especializado em gêneros nordestinos e Pop.",
    tags: ["Produção", "Pop", "Gravação"],
  },
  {
    id: 9,
    user: { name: "Banda Os Elétricos", avatarUrl: "https://i.pravatar.cc/150?img=10" },
    title: "Vocalista com drive para banda de Hard Rock",
    location: "Brasília, DF",
    description: "Banda de Hard Rock anos 80 (Guns, Bon Jovi) procura vocalista com bom alcance e drive na voz.",
    tags: ["Vocal", "Rock", "Entrar em uma banda"],
  },
  {
    id: 10,
    user: { name: "Beatriz Costa", avatarUrl: "https://i.pravatar.cc/150?img=11" },
    title: "Saxofonista para banda de Jazz e Blues",
    location: "São Paulo, SP",
    description: "Procuro banda ou músicos para tocar Jazz e Blues em bares e casas noturnas. Tenho sax alto e tenor.",
    tags: ["Saxofone", "Jazz", "Blues", "Entrar em uma banda"],
  },
  {
    id: 11,
    user: { name: "Ricardo Nunes", avatarUrl: "https://i.pravatar.cc/150?img=12" },
    title: "Baixista de Funk/Soul disponível",
    location: "Rio de Janeiro, RJ",
    description: "Baixista com groove e pegada de funk/soul procura projetos para shows e gravações. Influências: James Brown, Tim Maia.",
    tags: ["Baixo", "Funk", "Soul", "Freelancer"],
  },
  {
    id: 12,
    user: { name: "The Garage Band", avatarUrl: "https://i.pravatar.cc/150?img=13" },
    title: "Guitarrista base para banda de Indie Rock",
    location: "Belo Horizonte, MG",
    description: "Banda autoral de Indie Rock busca guitarrista base com equipamento próprio e vontade de compor.",
    tags: ["Guitarra", "Rock", "Indie", "Entrar em uma banda"],
  },
  {
    id: 13,
    user: { name: "Clara Ferreira", avatarUrl: "https://i.pravatar.cc/150?img=14" },
    title: "Cantora de Sertanejo para dupla",
    location: "Goiânia, GO",
    description: "Procuro primeira voz para formar dupla sertaneja. Foco em repertório universitário e composições próprias.",
    tags: ["Vocal", "Sertanejo", "Entrar em uma banda"],
  },
  {
    id: 14,
    user: { name: "Daniel Oliveira", avatarUrl: "https://i.pravatar.cc/150?img=15" },
    title: "Baterista de Reggae/Dub",
    location: "Florianópolis, SC",
    description: "Baterista com experiência em reggae e dub disponível para bandas e projetos na região da grande Florianópolis.",
    tags: ["Bateria", "Reggae", "Freelancer"],
  },
  {
    id: 15,
    user: { name: "Mariana Santos", avatarUrl: "https://i.pravatar.cc/150?img=16" },
    title: "Pianista para aulas e acompanhamento",
    location: "Curitiba, PR",
    description: "Ofereço aulas de piano e teclado para iniciantes, além de serviço de acompanhamento para cantores e instrumentistas.",
    tags: ["Teclado", "Aulas", "Freelancer"],
  },
  {
    id: 16,
    user: { name: "Projeto Acústico", avatarUrl: "https://i.pravatar.cc/150?img=17" },
    title: "Violonista para voz e violão",
    location: "Porto Alegre, RS",
    description: "Cantora procura violonista para projeto de voz e violão, com foco em MPB e Pop Rock nacional.",
    tags: ["Violão", "MPB", "Pop", "Show/Evento"],
  },
  {
    id: 17,
    user: { name: "Felipe Almeida", avatarUrl: "https://i.pravatar.cc/150?img=18" },
    title: "Técnico de som para eventos",
    location: "São Paulo, SP",
    description: "Técnico de som com equipamento próprio (PA e monitor) para shows de pequeno e médio porte.",
    tags: ["Técnico de Som", "Show/Evento", "Freelancer"],
  },
  {
    id: 18,
    user: { name: "Banda Reverb", avatarUrl: "https://i.pravatar.cc/150?img=19" },
    title: "Baixista para banda de Post-Punk",
    location: "Recife, PE",
    description: "Banda de post-punk/new wave (The Cure, Joy Division) procura baixista com timbre característico do estilo.",
    tags: ["Baixo", "Rock", "Post-Punk", "Entrar em uma banda"],
  },
  {
    id: 19,
    user: { name: "Letícia Barros", avatarUrl: "https://i.pravatar.cc/150?img=20" },
    title: "Vocalista para banda de Casamento",
    location: "Campinas, SP",
    description: "Banda de eventos procura vocalista feminina versátil, com repertório que vai do pop ao samba.",
    tags: ["Vocal", "Pop", "Samba", "Show/Evento"],
  },
  {
    id: 20,
    user: { name: "Gustavo Pereira", avatarUrl: "https://i.pravatar.cc/150?img=21" },
    title: "DJ para festas e eventos",
    location: "Rio de Janeiro, RJ",
    description: "DJ com foco em música eletrônica (House, Techno) e Funk. Equipamento completo para animar sua festa.",
    tags: ["DJ", "Eletrônica", "Funk", "Show/Evento"],
  },
  {
    id: 21,
    user: { name: "Orquestra Jovem", avatarUrl: "https://i.pravatar.cc/150?img=22" },
    title: "Violoncelista para orquestra",
    location: "Belo Horizonte, MG",
    description: "Orquestra jovem abre audição para vaga de violoncelista. Necessário leitura de partitura.",
    tags: ["Violoncelo", "Clássico", "Entrar em uma banda"],
  },
  {
    id: 22,
    user: { name: "André Souza", avatarUrl: "https://i.pravatar.cc/150?img=23" },
    title: "Guitarrista de Blues",
    location: "São Paulo, SP",
    description: "Guitarrista apaixonado por blues (B.B. King, Stevie Ray Vaughan) procura músicos para jam sessions e shows.",
    tags: ["Guitarra", "Blues", "Freelancer"],
  },
  {
    id: 23,
    user: { name: "Carolina Martins", avatarUrl: "https://i.pravatar.cc/150?img=24" },
    title: "Backing vocal para estúdio",
    location: "Salvador, BA",
    description: "Ofereço serviço de backing vocal para gravações. Afinação e experiência com harmonias vocais.",
    tags: ["Vocal", "Gravação", "Freelancer"],
  },
  {
    id: 24,
    user: { name: "Banda Forró Quente", avatarUrl: "https://i.pravatar.cc/150?img=25" },
    title: "Sanfoneiro para banda de forró",
    location: "Fortaleza, CE",
    description: "Banda de forró pé-de-serra procura sanfoneiro para temporada de shows. Repertório de Luiz Gonzaga a Falamansa.",
    tags: ["Sanfona", "Forró", "Entrar em uma banda"],
  },
  {
    id: 25,
    user: { name: "Rodrigo Lima", avatarUrl: "https://i.pravatar.cc/150?img=26" },
    title: "Baterista para banda de Pop Punk",
    location: "Curitiba, PR",
    description: "Banda de pop punk (Blink-182, Green Day) procura baterista com energia e pegada.",
    tags: ["Bateria", "Pop", "Punk", "Entrar em uma banda"],
  },
  {
    id: 26,
    user: { name: "Isabela Rocha", avatarUrl: "https://i.pravatar.cc/150?img=27" },
    title: "Letrista e compositora",
    location: "Online",
    description: "Escrevo letras e componho melodias para artistas de diversos gêneros. Parcerias via internet.",
    tags: ["Composição", "Letrista", "Gravação"],
  },
  {
    id: 27,
    user: { name: "Thiago Mendes", avatarUrl: "https://i.pravatar.cc/150?img=28" },
    title: "Trompetista para banda de Ska",
    location: "São Paulo, SP",
    description: "Procuro banda de ska ou músicos para montar um naipe de metais. Tenho trompete e flugelhorn.",
    tags: ["Trompete", "Ska", "Entrar em uma banda"],
  },
  {
    id: 28,
    user: { name: "Power Trio", avatarUrl: "https://i.pravatar.cc/150?img=29" },
    title: "Vocalista/Baixista para Power Trio",
    location: "Porto Alegre, RS",
    description: "Guitarrista e baterista procuram baixista que também cante para fechar um power trio de rock clássico.",
    tags: ["Baixo", "Vocal", "Rock", "Entrar em uma banda"],
  },
  {
    id: 29,
    user: { name: "Vanessa Gomes", avatarUrl: "https://i.pravatar.cc/150?img=30" },
    title: "Flautista para grupo de choro",
    location: "Rio de Janeiro, RJ",
    description: "Flautista transversal procura grupo de choro para ensaios e apresentações. Grande conhecimento do repertório.",
    tags: ["Flauta", "Choro", "Show/Evento"],
  },
  {
    id: 30,
    user: { name: "Bruno Castro", avatarUrl: "https://i.pravatar.cc/150?img=31" },
    title: "Violonista 7 cordas para samba",
    location: "Belo Horizonte, MG",
    description: "Violonista de 7 cordas disponível para acompanhar cantores(as) e grupos de samba e choro.",
    tags: ["Violão", "Samba", "Choro", "Freelancer"],
  },
  {
    id: 31,
    user: { name: "Laura Azevedo", avatarUrl: "https://i.pravatar.cc/150?img=32" },
    title: "Harpista para eventos",
    location: "Brasília, DF",
    description: "Harpista profissional para casamentos, coquetéis e eventos que exigem um toque de sofisticação.",
    tags: ["Harpa", "Clássico", "Show/Evento"],
  },
  {
    id: 32,
    user: { name: "Metalcore Project", avatarUrl: "https://i.pravatar.cc/150?img=33" },
    title: "Vocalista (gutural e melódico) para Metalcore",
    location: "Joinville, SC",
    description: "Banda de Metalcore com material próprio procura vocalista que domine tanto o canto gutural quanto o melódico.",
    tags: ["Vocal", "Metal", "Entrar em uma banda"],
  },
  {
    id: 33,
    user: { name: "Eduardo Jorge", avatarUrl: "https://i.pravatar.cc/150?img=34" },
    title: "Cavaquinista para roda de samba",
    location: "São Paulo, SP",
    description: "Cavaquinista com experiência procura rodas de samba para tocar aos finais de semana.",
    tags: ["Cavaquinho", "Samba", "Show/Evento"],
  },
  {
    id: 34,
    user: { name: "Patrícia Ramos", avatarUrl: "https://i.pravatar.cc/150?img=35" },
    title: "Professora de canto",
    location: "Online",
    description: "Aulas de canto popular online. Técnica vocal, afinação, respiração e repertório. Primeira aula experimental gratuita.",
    tags: ["Vocal", "Aulas", "Online"],
  },
  {
    id: 35,
    user: { name: "Synthwave Dreams", avatarUrl: "https://i.pravatar.cc/150?img=36" },
    title: "Produtor de Synthwave busca vocalista",
    location: "Curitiba, PR",
    description: "Produtor de synthwave/retrowave procura vocalista (masculino ou feminino) para projeto autoral com influências dos anos 80.",
    tags: ["Vocal", "Eletrônica", "Synthwave", "Gravação"],
  },
  {
    id: 36,
    user: { name: "Marcelo Vieira", avatarUrl: "https://i.pravatar.cc/150?img=37" },
    title: "Gaitista de Blues/Folk",
    location: "Belo Horizonte, MG",
    description: "Gaitista (diatônica e cromática) disponível para shows acústicos, bandas de blues, folk e rock.",
    tags: ["Gaita", "Blues", "Folk", "Freelancer"],
  },
  {
    id: 37,
    user: { name: "Amanda Lins", avatarUrl: "https://i.pravatar.cc/150?img=38" },
    title: "Ukulelista para luau e eventos praianos",
    location: "Florianópolis, SC",
    description: "Canto e toco ukulele, ideal para luais, eventos em quiosques e festas com tema praiano. Repertório pop e reggae.",
    tags: ["Ukulele", "Vocal", "Pop", "Show/Evento"],
  },
  {
    id: 38,
    user: { name: "Heavy Metal Tribute", avatarUrl: "https://i.pravatar.cc/150?img=39" },
    title: "Baixista para tributo Iron Maiden/Judas Priest",
    location: "Rio de Janeiro, RJ",
    description: "Banda tributo a clássicos do Heavy Metal procura baixista com pegada, equipamento de qualidade e disponibilidade para ensaios.",
    tags: ["Baixo", "Metal", "Entrar em uma banda"],
  },
  {
    id: 39,
    user: { name: "Fábio Teixeira", avatarUrl: "https://i.pravatar.cc/150?img=40" },
    title: "Luthier - Regulagem e reparo",
    location: "São Paulo, SP",
    description: "Serviços de regulagem, reparo e customização de guitarras, baixos e violões. Deixe seu instrumento tinindo!",
    tags: ["Luthier", "Regulagem", "Reparo"],
  },
  {
    id: 40,
    user: { name: "Roda de Choro", avatarUrl: "https://i.pravatar.cc/150?img=41" },
    title: "Pandeirista para grupo de Choro",
    location: "Brasília, DF",
    description: "Grupo de choro consolidado procura pandeirista com experiência no gênero para apresentações regulares.",
    tags: ["Pandeiro", "Choro", "Show/Evento"],
  },
  {
    id: 41,
    user: { name: "Júlia Magalhães", avatarUrl: "https://i.pravatar.cc/150?img=42" },
    title: "Violonista clássica para recitais",
    location: "Porto Alegre, RS",
    description: "Violonista com formação erudita disponível para recitais solo, música de câmara e eventos formais.",
    tags: ["Violão", "Clássico", "Show/Evento"],
  },
  {
    id: 42,
    user: { name: "Groove Machine", avatarUrl: "https://i.pravatar.cc/150?img=43" },
    title: "Tecladista para banda de Disco/Funk",
    location: "Salvador, BA",
    description: "Banda de Disco Music e Funk dos anos 70 procura tecladista que domine timbres de Rhodes, Clavinet e sintetizadores da época.",
    tags: ["Teclado", "Funk", "Disco", "Entrar em uma banda"],
  },
  {
    id: 43,
    user: { name: "Sérgio Barros", avatarUrl: "https://i.pravatar.cc/150?img=44" },
    title: "Baterista de Jazz/Fusion",
    location: "Curitiba, PR",
    description: "Baterista versátil com foco em Jazz, Fusion e música instrumental brasileira. Disponível para shows e gravações.",
    tags: ["Bateria", "Jazz", "Fusion", "Freelancer"],
  },
  {
    id: 44,
    user: { name: "Renata Fagundes", avatarUrl: "https://i.pravatar.cc/150?img=45" },
    title: "Vocalista para banda de R&B/Soul",
    location: "Belo Horizonte, MG",
    description: "Procuro músicos para montar uma banda de R&B e Soul contemporâneo. Influências: H.E.R., Daniel Caesar, Jorja Smith.",
    tags: ["Vocal", "Soul", "R&B", "Entrar em uma banda"],
  },
  {
    id: 45,
    user: { name: "Paulo Henrique", avatarUrl: "https://i.pravatar.cc/150?img=46" },
    title: "Mixagem e Masterização Online",
    location: "Online",
    description: "Serviços de mixagem e masterização para sua música. Deixe sua gravação com som profissional. Preços acessíveis.",
    tags: ["Mixagem", "Masterização", "Gravação"],
  },
  {
    id: 46,
    user: { name: "Trio MPB", avatarUrl: "https://i.pravatar.cc/150?img=47" },
    title: "Percussionista para trio de MPB",
    location: "Rio de Janeiro, RJ",
    description: "Trio de voz, violão e baixo procura percussionista (cajón, bongô, etc) para shows em bares na Zona Sul.",
    tags: ["Percussão", "MPB", "Show/Evento"],
  },
  {
    id: 47,
    user: { name: "Otávio Rocha", avatarUrl: "https://i.pravatar.cc/150?img=48" },
    title: "Guitarrista de Jazz Manouche",
    location: "São Paulo, SP",
    description: "Guitarrista no estilo de Django Reinhardt procura músicos (violino, outro violão, baixo acústico) para formar grupo de Jazz Manouche.",
    tags: ["Guitarra", "Jazz", "Entrar em uma banda"],
  },
  {
    id: 48,
    user: { name: "Banda de Baile", avatarUrl: "https://i.pravatar.cc/150?img=49" },
    title: "Trombonista para banda de baile",
    location: "Fortaleza, CE",
    description: "Banda de baile com agenda cheia procura trombonista para completar naipe de metais. Leitura à primeira vista é um diferencial.",
    tags: ["Trombone", "Show/Evento", "Freelancer"],
  },
  {
    id: 49,
    user: { name: "Camila Neves", avatarUrl: "https://i.pravatar.cc/150?img=50" },
    title: "Vocalista para gravação de jingles",
    location: "Online",
    description: "Tenho home studio e gravo vozes para jingles comerciais, spots de rádio e vídeos institucionais. Entrega rápida.",
    tags: ["Vocal", "Gravação", "Jingle", "Freelancer"],
  },
  {
    id: 50,
    user: { name: "Death Metal Legion", avatarUrl: "https://i.pravatar.cc/150?img=51" },
    title: "Baterista para banda de Death Metal",
    location: "Manaus, AM",
    description: "Banda de Death Metal procura baterista com técnica (blast beats, pedal duplo) e compromisso para ensaios e composições.",
    tags: ["Bateria", "Metal", "Entrar em uma banda"],
  },
];