// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rdzvgueefbrqscirrgqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkenZndWVlZmJycXNjaXJyZ3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyOTk5MjksImV4cCI6MjA3MDg3NTkyOX0.oV8gj-o-B61Z0xD4wqLxoI2U48VD4dG_DadNrrFWiz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);